const YELLOW = '#FFD44A'
const NAVY_BLUE = '#001C3D'
const OLIVE ='#637B4C'
const LIGHT_GRAY = '#D9DCE7'
const LIGHT_GRAY_FOREGROUND = '#F6F7F9'
const TURQUOISE = '#4A9497'

export const colors = {
YELLOW,
NAVY_BLUE,
OLIVE,
LIGHT_GRAY,
TURQUOISE,
LIGHT_GRAY_FOREGROUND,

PRIMARY: NAVY_BLUE,
COMPLEMENTARY: YELLOW,
ACCENT: TURQUOISE,
WHITE: LIGHT_GRAY_FOREGROUND
}
