import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

/* 

@@ -1,30 +0,0 @@
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Manny Ikomi</title>   <link rel="stylesheet" href="/css/styles.css">

</head>
<body>
  
</body>
</html>
*/

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Manny Ikomi</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      Test render
      <section>
        <img src="" alt="Manny smiling" />
        <h1>
          I use <span>design</span> to take
          <span>people</span>
          from what-is, to what-ought-to-be.
        </h1>
      </section>
      <section>
        <h2>Hi, I’m Manny!</h2>
        <h3>UX designer, lifetime learner, digital craftsman.</h3>
        <p>
          I’m a cross-functional creative specializing in user experience that
          thrives at the intersections of design, technology and people.
          Currently I’m working at IBM iX as an Associate UX Design consultant.
        </p>
        <p>
          When I’m not working you might be able to catch me streaming design
          and web development on twitch or rollerskating to finally get away
          from my desk!
        </p>
        <a href="https://poly.mannyikomi.com">Polywork =></a>
      </section>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
